### ISSUE TITLE
Critical warning message while opening project

### ISSUE THREAD

**Issue by bzboi** [MorgothCreator/Verilog_SSD1306_CFG_IP#1]
Opening the project in vivado results in the following warning :-
" [Project 1-311] Could not find the file 'C:/Users/test/Downloads/fpga/Verilog_SPI_MASTER_INTERFACE/SPI.srcs/sources_1/new/spi_master.v', nor could it be found using path 'C:/GitHub/Verilog_SPI_MASTER_INTERFACE/SPI.srcs/sources_1/new/spi_master.v'."
Where can I find Verilog_SPI_MASTER_INTERFACE repo? Thanks.

**Comment by MorgothCreator** [comment]
https://github.com/MorgothCreator/VerilogUtilIP/blob/master/spi_master.v
